version: '3.9'

services:
  postgre:
    image: postgres:14.5-alpine
    container_name: postgre
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  pg-admin:
#    image: dpage/pgadmin4:6.13
#    container_name: pg-admin
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.org
#      - PGADMIN_DEFAULT_PASSWORD=root
#      - PGADMIN_LISTEN_PORT=5050
#    ports:
#      - "5050:5050"
