### read gauge by JSON
POST http://localhost:8080/value
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "id": "testGauge",
  "type": "gauge"
}

### update gauge by JSON
POST http://localhost:8080/update
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "id": "testGauge",
  "type": "gauge",
  "value": 12345
}

### read counter by JSON
POST http://localhost:8080/value
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "id": "testCounter",
  "type": "counter"
}

### update counter by JSON
POST http://localhost:8080/update
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "id": "testCounter",
  "type": "counter",
  "delta": 123456
}

### get all metrics
GET http://localhost:8080/
Accept-Encoding: gzip, deflate, br
Content-Type: text/html

### update batch
POST http://localhost:8080/updates
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

[
  {
    "id": "batchCounter1",
    "type": "counter",
    "delta": 100
  },
  {
    "id": "batchCounter2",
    "type": "counter",
    "delta": 200
  },
  {
    "id": "batchGauge1",
    "type": "gauge",
    "value": 1000
  },
  {
    "id": "batchGauge2",
    "type": "gauge",
    "value": 2000
  },
  {
    "id": "testCounter",
    "type": "counter",
    "delta": 123456
  }
]

### ping
GET http://localhost:8080/ping

