### check DB connection
GET http://localhost:8080/ping

### get all metrics
GET http://localhost:8080/
Accept-Encoding: gzip, deflate, br
Content-Type: text/html

### update gauge by URL [200]
POST http://localhost:8080/update/gauge/urlGauge/13

### update gauge by URL (invalid - no value [400])
POST http://localhost:8080/update/gauge/urlGauge

### update gauge by URL (invalid - no name [404])
POST http://localhost:8080/update/gauge/

### read gauge by URL
GET http://localhost:8080/value/gauge/urlGauge

### update counter by URL
POST http://localhost:8080/update/counter/urlCounter/7

### update counter by URL (invalid - no value [400])
POST http://localhost:8080/update/counter/urlCounter

### update counter by URL (invalid - no name [404])
POST http://localhost:8080/update/counter

### read counter by URL
GET http://localhost:8080/value/counter/urlCounter

### update by URL (invalid - unknown type)
POST http://localhost:8080/update/unknown/urlUnknown/999

### update gauge by JSON
POST http://localhost:8080/update
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "id": "jsonGauge",
  "type": "gauge",
  "value": 13579
}

### read gauge by JSON
POST http://localhost:8080/value/
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "id": "testGauge",
  "type": "gauge"
}

### update counter by JSON
POST http://localhost:8080/update
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "id": "jsonCounter",
  "type": "counter",
  "delta": 777
}

### read counter by JSON
POST http://localhost:8080/value
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

{
  "id": "testCounter",
  "type": "counter"
}

### update batch
POST http://localhost:8080/updates
Accept-Encoding: gzip, deflate, br
Content-Type: application/json

[
  {
    "id": "batchCounter1",
    "type": "counter",
    "delta": -1
  },
  {
    "id": "batchCounter2",
    "type": "counter",
    "delta": 1
  },
  {
    "id": "batchGauge1",
    "type": "gauge",
    "value": 1407
  },
  {
    "id": "batchGauge2",
    "type": "gauge",
    "value": 999
  },
  {
    "id": "testCounter",
    "type": "counter",
    "delta": 617281
  }
]
